#pragma once

namespace io
{
	#ifdef WINDOWS_PLATFORM

	#define RED	  (FOREGROUND_INTENSITY | FOREGROUND_RED)
	#define GREEN (FOREGROUND_INTENSITY | FOREGROUND_GREEN)
	#define WHITE (FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE)

	#define YELLOW  (FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN)
	#define MAGENTA (FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN)

	#endif
}